# -*- coding: utf-8 -*-
"""Sales Data Analysis & Visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aB0d1b0sb4MybjtQqqBr6nzYgSyUOjo0
"""

from google.colab import drive
drive.mount('/content/drive')

import zipfile

zip_path = "/content/drive/My Drive/store-sales-time-series-forecasting.zip"  # Dosya yolunu değiştir!
extract_path = "/content/data"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dosyalar başarıyla açıldı!")

!ls /content

import os

data_path = "/content/data"  # Dosyaların olduğu klasör
files = os.listdir(data_path)
print("📂 Veriler:", files)

import pandas as pd

# Verinin yolu
csv_path = "/content/data/train.csv"

# CSV dosyası
df = pd.read_csv(csv_path)

# İlk birkaç satır
df.head()

df.shape

df.info()

df.isnull().sum()

df.describe()

# date sütununu datetime formatına çevir
df["date"] = pd.to_datetime(df["date"])

# Veriyi tarihe göre sırala
df = df.sort_values("date")

# Tarihe göre satışları çiz
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 5))
plt.plot(df.groupby("date")["sales"].sum(), label="Toplam Satış", color="royalblue")
plt.xlabel("Tarih")
plt.ylabel("Toplam Satış")
plt.title("Zaman Serisi: Günlük Toplam Satışlar")
plt.legend()
plt.show()

df["date"] = pd.to_datetime(df["date"])

df.set_index("date", inplace=True)  # Tarihi index olarak ayarla
monthly_sales = df.resample("M")["sales"].mean()  # Aylık ortalama satışları hesapla

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))
plt.plot(monthly_sales, marker="o", linestyle="-", color="b")
plt.title("Aylık Ortalama Satışlar")
plt.xlabel("Tarih")
plt.ylabel("Satış Ortalaması")
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Histogram çizimi
plt.figure(figsize=(10, 6))
sns.histplot(df['sales'], bins=50, kde=True, color='blue')

# Başlık ve etiketler
plt.title('Satış Dağılımı', fontsize=14)
plt.xlabel('Satış Miktarı', fontsize=12)
plt.ylabel('Frekans', fontsize=12)

# Grafiği göster
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(df[df['sales'] < 1000]['sales'], bins=50, kde=True, color='blue')  # 1000 üzerindeki satışları hariç tut
plt.title('Satış Dağılımı (Outlier Kısıtlamalı)', fontsize=14)
plt.xlabel('Satış Miktarı', fontsize=12)
plt.ylabel('Frekans', fontsize=12)

plt.show()

import numpy as np

plt.figure(figsize=(10, 6))
sns.histplot(np.log1p(df['sales']), bins=50, kde=True, color='blue')  # log dönüşümüyle daha dengeli dağılım

plt.title('Log Dönüşümlü Satış Dağılımı', fontsize=14)
plt.xlabel('Log(Satış Miktarı)', fontsize=12)
plt.ylabel('Frekans', fontsize=12)

plt.show()

